# Generated by Django 3.0.5 on 2020-05-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='latest news', max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('caption', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='feeds')),
            ],
        ),
    ]
