# Generated by Django 3.0.5 on 2020-06-02 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeds',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 2, 13, 7, 59, 375643)),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='caption',
            field=models.CharField(default='mews', max_length=50),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='description',
            field=models.CharField(default='my news', max_length=200),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='file',
            field=models.FileField(default='default.jpg', upload_to='feeds'),
        ),
    ]
