# Generated by Django 3.0.5 on 2020-06-02 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200602_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeds',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 2, 13, 24, 23, 148560)),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='title',
            field=models.CharField(choices=[('crime', 'crime'), ('sports', 'sports'), ('film', 'film'), ('politics', 'politics'), ('city', 'city'), ('country', 'country')], default='latest news', max_length=100),
        ),
    ]
