# Generated by Django 3.0.5 on 2020-06-02 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200602_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_paper', models.FileField(upload_to='news_paper')),
            ],
        ),
        migrations.AlterField(
            model_name='feeds',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 2, 14, 44, 7, 643555)),
        ),
    ]
