# Generated by Django 3.0.5 on 2020-06-02 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200602_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeds',
            name='caption',
            field=models.CharField(default='news', max_length=50),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 2, 20, 37, 41, 615685), verbose_name='pubdate'),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='description',
            field=models.CharField(default='my news', max_length=2000),
        ),
    ]
